important_angles: [
    left_knee,
    right_knee,
    left_hip,
    right_hip
]
reference_table: 
  start:
    left_knee: 175
    right_knee: 175
    left_hip: 175
    right_hip: 175
  mid:
    left_knee: 50
    right_knee: 50
    left_hip: 55
    right_hip: 55
  finish:
    left_knee: 175
    right_knee: 175
    left_hip: 175
    right_hip: 175

