important_angles: [
    left_knee,
    right_knee,
    left_hip,
    right_hip
]
reference_table: 
  start:
    left_knee: 170
    right_knee: 170
    left_hip: 175
    right_hip: 175
  mid:
    left_knee: 92
    right_knee: 75
    left_hip: 163
    right_hip: 95
  finish:
    left_knee: 170
    right_knee: 170
    left_hip: 175
    right_hip: 175

