important_angles: [
    left_knee,
    right_knee,
    left_hip,
    right_hip
]
reference_table: 
  start:
    left_knee: 175
    right_knee: 175
    left_hip: 175
    right_hip: 175
  mid:
    left_knee: 55
    right_knee: 55
    left_hip: 40
    right_hip: 40
  finish:
    left_knee: 175
    right_knee: 175
    left_hip: 175
    right_hip: 175

